package test;


import Ventanas.JPanelAgregarProductos;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cruzh
 */
public class ContraAlmacen extends javax.swing.JPanel {

    /**
     * Creates new form ContraAlmacen
     */
    public ContraAlmacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldContra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnIgresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(90, 185, 225));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldContra.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldContra.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldContra.setBorder(null);
        add(jTextFieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 500, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 60));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTextFieldUsuarioComponentRemoved(evt);
            }
        });
        add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 500, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Aqui va e logo de la empresa cuando el diseñador me lo pase en png unu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 680, 120));

        BtnIgresar.setBackground(new java.awt.Color(246, 229, 186));
        BtnIgresar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnIgresar.setForeground(new java.awt.Color(0, 0, 0));
        BtnIgresar.setText("   Ingresar");
        BtnIgresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnIgresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIgresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIgresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIgresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIgresarMouseExited(evt);
            }
        });
        add(BtnIgresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 150, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioComponentRemoved
      
    }//GEN-LAST:event_jTextFieldUsuarioComponentRemoved

    private void BtnIgresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIgresarMouseClicked

                String usuario = jTextFieldUsuario.getText();
        String password = jTextFieldContra.getText();
        if(usuario.isEmpty() || password.isEmpty() ){
           JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");  
       }
       else {
           if (usuario.equals("Admin01") && password.equals(password)){
               JOptionPane.showMessageDialog(null,"Bienvenido");
               JPanelAgregarProductos puente = new JPanelAgregarProductos();
               puente.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null, "La contraseña o el usuario son incorrectos");
           }
       }
        this.limpiar();
    }//GEN-LAST:event_BtnIgresarMouseClicked

    private void BtnIgresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIgresarMouseEntered
        BtnIgresar.setBackground(Color.orange);
    }//GEN-LAST:event_BtnIgresarMouseEntered

    private void BtnIgresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIgresarMouseExited
        BtnIgresar.setBackground(new Color (186,202,246));
    }//GEN-LAST:event_BtnIgresarMouseExited
 public void limpiar (){
        jTextFieldUsuario.setText("");
        jTextFieldContra.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnIgresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldContra;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
