package test;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author cruzh
 */
import Ventanas.JPanelAgregarProductos;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
public class login extends javax.swing.JDialog {
    String nino;

    /**
     * Creates new form login
     */
    public login(java.awt.Frame parent, boolean modal,JFrame jf) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(jf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDialog = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDialog.setBackground(new java.awt.Color(250, 186, 86));
        jPanelDialog.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanelDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanelDialog.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese contraseña");
        jPanelDialog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 240, 50));

        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAceptar.setText("aceptar");
        BtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanelDialog.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 60));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelDialog.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 340, 50));

        getContentPane().add(jPanelDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        nino=jPasswordField1.getText();
        if(nino.equals("password")){
        this.dispose();
        JPanelAgregarProductos miku = new JPanelAgregarProductos();
        miku.setSize(1330, 620);
        miku.setLocation(0,0);
        Pruebas.jPanelAcciones.removeAll();
        Pruebas.jPanelAcciones.add(miku, BorderLayout.CENTER);
        Pruebas.jPanelAcciones.revalidate();
        Pruebas.jPanelAcciones.repaint();
        }else{
            JOptionPane.showMessageDialog(null,"Contraseña incorrecta");
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                login dialog = new login(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDialog;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
