package test;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class LoginPrincipal extends javax.swing.JFrame {
    String miku, nino;
    int mousex, mousey;

    /**
     * Creates new form LoginPrincipal
     */
    public LoginPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JPassword = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelMOVER = new javax.swing.JPanel();
        jPanelcerrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(117, 172, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(15, 117, 189));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INICIAR SESION");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("BIENVENIDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 20));

        txtuser.setBackground(new java.awt.Color(255, 255, 255));
        txtuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(0, 0, 0));
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("CONTRASEÑA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 171, 30));

        JPassword.setBackground(new java.awt.Color(255, 255, 255));
        JPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JPassword.setForeground(new java.awt.Color(0, 0, 0));
        JPassword.setBorder(null);
        JPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPasswordMousePressed(evt);
            }
        });
        jPanel1.add(JPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 360, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 420, 450));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondologin.png"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 450));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 390, 450));

        jPanelMOVER.setBackground(new java.awt.Color(15, 117, 189));
        jPanelMOVER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelMOVERMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelMOVERMouseMoved(evt);
            }
        });
        jPanelMOVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelMOVERMousePressed(evt);
            }
        });
        jPanelMOVER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelcerrar.setBackground(new java.awt.Color(15, 117, 189));
        jPanelcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelcerrarMouseExited(evt);
            }
        });
        jPanelcerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("X");
        jPanelcerrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanelMOVER.add(jPanelcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(jPanelMOVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if(txtuser.getText().equals("User1")&&JPassword.getText().equals("123456789")){
            JOptionPane.showMessageDialog(null, "TODO SALIO BIEN");
            Pruebas miku = new Pruebas();
            miku.setVisible(true);
            this.dispose();
    }else{
        JOptionPane.showMessageDialog(null, "Usuario o contraseña invalidos");
    }
            
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanelMOVERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMOVERMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jPanelMOVERMouseDragged

    private void jPanelMOVERMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMOVERMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelMOVERMouseMoved

    private void jPanelMOVERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMOVERMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanelMOVERMousePressed

    private void jPanelcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelcerrarMouseEntered
        jPanelcerrar.setBackground(Color.red);
    }//GEN-LAST:event_jPanelcerrarMouseEntered

    private void jPanelcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelcerrarMouseExited
        jPanelcerrar.setBackground(new Color(15,117,189));
    }//GEN-LAST:event_jPanelcerrarMouseExited

    private void jPanelcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelcerrarMouseClicked
        this.Cerrar();
    }//GEN-LAST:event_jPanelcerrarMouseClicked

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if (txtuser.getText().equals("Ingrese el usuario")){
        txtuser.setText("");
        txtuser.setForeground(Color.BLACK);
        }
        if (String.valueOf(JPassword.getPassword()).isEmpty()){
        JPassword.setText("**********");
        JPassword.setForeground(new Color (204,204,204));
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void JPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPasswordMousePressed
       if(String.valueOf(JPassword.getPassword()).equals("**********")){
        JPassword.setText("");
        JPassword.setForeground(Color.BLACK);
       }
       if(txtuser.getText().isEmpty()){
        txtuser.setText("Ingrese el usuario");
        txtuser.setForeground(new Color (204,204,204));
       }
    }//GEN-LAST:event_JPasswordMousePressed
    private void Cerrar(){
    String botones [] = {"Cerrar", "Cancelar"};
    int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicacion?", "ATENCIÓN",
            0, 2, null, botones,this);
    if(eleccion==JOptionPane.YES_OPTION){
        System.exit(0);
    }else if (eleccion==JOptionPane.NO_OPTION){
        JOptionPane.showMessageDialog(null,"Se cancelo el cierre de la aplicacion");
    
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelMOVER;
    private javax.swing.JPanel jPanelcerrar;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
