package test;

import mesas.Palapa3;
import mesas.Palapa2;
import mesas.Palapa1;
import Ventanas.JPanelAgregarProductos;
import Ventanas.JPanelGenreal;
import mesas.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cruzh
 */
public class Pruebas extends javax.swing.JFrame {
    int mousex, mousey;
    String cont;

    /**
     * Creates new form Pruebas
     */
    public Pruebas() {
        initComponents();
//        mostrarg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAcciones = new javax.swing.JPanel();
        jPanelMesa2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanelMesa1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelMesa4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanelMesa3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanelMesa5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanelMesa7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanelMesa6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanelMesa8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanelMesa9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanelMesa10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanelPalapa1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanelMesa15 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanelMesa12 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanelMesa13 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanelMesa14 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanelMesa011 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanelPalapa2 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanelPalapa3 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jlabelfondo = new javax.swing.JLabel();
        JpanelMover = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BtnInventario = new javax.swing.JLabel();
        jPanelVisualizar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelGeneral = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAcciones.setBackground(new java.awt.Color(117, 172, 211));
        jPanelAcciones.setLayout(null);

        jPanelMesa2.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa2MouseExited(evt);
            }
        });
        jPanelMesa2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel13.setText("MESA 2");
        jPanelMesa2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa2);
        jPanelMesa2.setBounds(251, 34, 170, 169);

        jPanelMesa1.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa1MouseExited(evt);
            }
        });
        jPanelMesa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel16.setText("MESA 1");
        jPanelMesa1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jPanelAcciones.add(jPanelMesa1);
        jPanelMesa1.setBounds(32, 34, 170, 169);

        jPanelMesa4.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa4MouseExited(evt);
            }
        });
        jPanelMesa4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel18.setText("MESA 4");
        jPanelMesa4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa4);
        jPanelMesa4.setBounds(689, 34, 170, 169);

        jPanelMesa3.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa3MouseExited(evt);
            }
        });
        jPanelMesa3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel20.setText("MESA 3");
        jPanelMesa3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa3);
        jPanelMesa3.setBounds(465, 34, 170, 169);

        jPanelMesa5.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa5MouseExited(evt);
            }
        });
        jPanelMesa5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel22.setText("MESA 5");
        jPanelMesa5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa5);
        jPanelMesa5.setBounds(906, 34, 170, 169);

        jPanelMesa7.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa7MouseExited(evt);
            }
        });
        jPanelMesa7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel24.setText("MESA 7");
        jPanelMesa7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa7);
        jPanelMesa7.setBounds(32, 242, 170, 169);

        jPanelMesa6.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa6MouseExited(evt);
            }
        });
        jPanelMesa6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel26.setText("MESA 6");
        jPanelMesa6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa6);
        jPanelMesa6.setBounds(1133, 34, 170, 169);

        jPanelMesa8.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa8MouseExited(evt);
            }
        });
        jPanelMesa8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel32.setText("MESA 8");
        jPanelMesa8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa8);
        jPanelMesa8.setBounds(251, 242, 170, 169);

        jPanelMesa9.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa9MouseExited(evt);
            }
        });
        jPanelMesa9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel28.setText("MESA 9");
        jPanelMesa9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa9);
        jPanelMesa9.setBounds(465, 242, 170, 166);

        jPanelMesa10.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa10MouseExited(evt);
            }
        });
        jPanelMesa10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel31.setText("MESA 10");
        jPanelMesa10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa10);
        jPanelMesa10.setBounds(689, 242, 170, 166);

        jPanelPalapa1.setBackground(new java.awt.Color(246, 229, 186));
        jPanelPalapa1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPalapa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPalapa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPalapa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPalapa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPalapa1MouseExited(evt);
            }
        });
        jPanelPalapa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel30.setText("PALAPA 1");
        jPanelPalapa1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/palaba 128px.png"))); // NOI18N
        jPanelPalapa1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelPalapa1);
        jPanelPalapa1.setBounds(689, 449, 170, 169);

        jPanelMesa15.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa15MouseExited(evt);
            }
        });
        jPanelMesa15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel43.setText("MESA 15");
        jPanelMesa15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa15);
        jPanelMesa15.setBounds(465, 449, 170, 166);

        jPanelMesa12.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa12MouseExited(evt);
            }
        });
        jPanelMesa12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel45.setText("MESA 12");
        jPanelMesa12.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa12.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa12);
        jPanelMesa12.setBounds(1133, 242, 170, 166);

        jPanelMesa13.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa13MouseExited(evt);
            }
        });
        jPanelMesa13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel47.setText("MESA 13");
        jPanelMesa13.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa13);
        jPanelMesa13.setBounds(32, 449, 170, 166);

        jPanelMesa14.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa14MouseExited(evt);
            }
        });
        jPanelMesa14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel49.setText("MESA 14");
        jPanelMesa14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa14);
        jPanelMesa14.setBounds(251, 449, 170, 166);

        jPanelMesa011.setBackground(new java.awt.Color(246, 229, 186));
        jPanelMesa011.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMesa011.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMesa011.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMesa011MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMesa011MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMesa011MouseExited(evt);
            }
        });
        jPanelMesa011.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel51.setText("MESA 11");
        jPanelMesa011.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa-de-cena 128px.png"))); // NOI18N
        jPanelMesa011.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelMesa011);
        jPanelMesa011.setBounds(906, 242, 170, 169);

        jPanelPalapa2.setBackground(new java.awt.Color(246, 229, 186));
        jPanelPalapa2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPalapa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPalapa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPalapa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPalapa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPalapa2MouseExited(evt);
            }
        });
        jPanelPalapa2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel53.setText("PALAPA 2");
        jPanelPalapa2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/palaba 128px.png"))); // NOI18N
        jPanelPalapa2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelPalapa2);
        jPanelPalapa2.setBounds(906, 449, 170, 166);

        jPanelPalapa3.setBackground(new java.awt.Color(246, 229, 186));
        jPanelPalapa3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPalapa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPalapa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPalapa3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPalapa3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPalapa3MouseExited(evt);
            }
        });
        jPanelPalapa3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel55.setText("PALAPA 3");
        jPanelPalapa3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/palaba 128px.png"))); // NOI18N
        jPanelPalapa3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jPanelAcciones.add(jPanelPalapa3);
        jPanelPalapa3.setBounds(1133, 449, 170, 166);

        jlabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoprincipal1.png"))); // NOI18N
        jPanelAcciones.add(jlabelfondo);
        jlabelfondo.setBounds(0, 0, 1330, 650);

        getContentPane().add(jPanelAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1330, 650));

        JpanelMover.setBackground(new java.awt.Color(255, 255, 255));
        JpanelMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JpanelMoverMouseDragged(evt);
            }
        });
        JpanelMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JpanelMoverMousePressed(evt);
            }
        });
        JpanelMover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(250, 186, 86));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("X");
        jPanelCerrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 30, 40));

        JpanelMover.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1278, 0, 52, 60));

        BtnInventario.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnInventario.setForeground(new java.awt.Color(128, 50, 69));
        BtnInventario.setText(" Productos");
        BtnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JpanelMover.add(BtnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 120, 54));

        jPanelVisualizar.setBackground(new java.awt.Color(243, 163, 38));
        jPanelVisualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVisualizarMouseClicked(evt);
            }
        });
        jPanelVisualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carrito-de-compras.png"))); // NOI18N
        jLabel12.setText("a");
        jPanelVisualizar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 12, 40, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Visualizar");
        jPanelVisualizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        JpanelMover.add(jPanelVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 190, 60));

        jPanelGeneral.setBackground(new java.awt.Color(243, 163, 38));
        jPanelGeneral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGeneralMouseClicked(evt);
            }
        });
        jPanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/hogar.png"))); // NOI18N
        jLabel10.setText("a");
        jPanelGeneral.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 30, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("General");
        jPanelGeneral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        JpanelMover.add(jPanelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 187, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/arriba2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        JpanelMover.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        getContentPane().add(JpanelMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        this.Cerrar();
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        jPanelCerrar.setBackground(Color.red);
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        jPanelCerrar.setBackground(new Color(250,186,86));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void JpanelMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelMoverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_JpanelMoverMouseDragged

    private void JpanelMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelMoverMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_JpanelMoverMousePressed

    private void jPanelMesa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa2MouseClicked
        Mesa02 miku = new Mesa02();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa2MouseClicked

    private void jPanelMesa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa1MouseClicked
        Mesa01 miku = new Mesa01();
        miku.setSize(1330, 620);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa1MouseClicked

    private void jPanelMesa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa4MouseClicked
        Mesa04 miku = new Mesa04();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa4MouseClicked

    private void jPanelMesa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa3MouseClicked
        Mesa03 miku = new Mesa03();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa3MouseClicked

    private void jPanelMesa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa5MouseClicked
        Mesa05 miku = new Mesa05();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa5MouseClicked

    private void jPanelMesa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa7MouseClicked
        Mesa07 miku = new Mesa07();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa7MouseClicked

    private void jPanelMesa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa6MouseClicked
        Mesa06 miku = new Mesa06();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa6MouseClicked

    private void jPanelMesa9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa9MouseClicked
        Mesa09 miku = new Mesa09();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa9MouseClicked

    private void jPanelPalapa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa1MouseClicked
        Palapa1 miku = new Palapa1();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelPalapa1MouseClicked

    private void jPanelMesa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa8MouseClicked
        Mesa08 miku = new Mesa08();
        miku.setSize(1330, 624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa8MouseClicked

    private void jPanelMesa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa1MouseEntered
        jPanelMesa1.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa1MouseEntered

    private void jPanelMesa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa1MouseExited
//        jPanelMesa1.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa1MouseExited

    private void jPanelMesa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa2MouseEntered
        jPanelMesa2.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa2MouseEntered

    private void jPanelMesa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa2MouseExited
//        jPanelMesa2.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa2MouseExited

    private void jPanelMesa3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa3MouseEntered
        jPanelMesa3.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa3MouseEntered

    private void jPanelMesa3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa3MouseExited
//        jPanelMesa3.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa3MouseExited

    private void jPanelMesa4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa4MouseEntered
        jPanelMesa4.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa4MouseEntered

    private void jPanelMesa4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa4MouseExited
//        jPanelMesa4.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa4MouseExited

    private void jPanelMesa5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa5MouseEntered
        jPanelMesa5.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa5MouseEntered

    private void jPanelMesa5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa5MouseExited
//        jPanelMesa5.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa5MouseExited

    private void jPanelMesa6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa6MouseEntered
        jPanelMesa6.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa6MouseEntered

    private void jPanelMesa6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa6MouseExited
//        jPanelMesa6.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa6MouseExited

    private void jPanelMesa7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa7MouseEntered
        jPanelMesa7.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa7MouseEntered

    private void jPanelMesa7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa7MouseExited
//        jPanelMesa7.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa7MouseExited

    private void jPanelMesa8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa8MouseEntered
        jPanelMesa8.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa8MouseEntered

    private void jPanelMesa8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa8MouseExited
//        jPanelMesa8.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa8MouseExited

    private void jPanelMesa9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa9MouseEntered
        jPanelMesa9.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa9MouseEntered

    private void jPanelMesa9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa9MouseExited
//        jPanelMesa9.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa9MouseExited

    private void jPanelPalapa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa1MouseEntered
        jPanelPalapa1.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelPalapa1MouseEntered

    private void jPanelPalapa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa1MouseExited
//        jPanelPalapa1.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelPalapa1MouseExited

    private void jPanelVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVisualizarMouseClicked
//          login yotsuba = new login(this,true, this);
//          yotsuba.setVisible(true);
        JPanelAgregarProductos miku = new JPanelAgregarProductos();
        //miku.setSize(1140, 560);
        miku.setSize(1330, 650);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
//this.contraseña();
    }//GEN-LAST:event_jPanelVisualizarMouseClicked

    private void jPanelGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGeneralMouseClicked
        Pruebas miku = new Pruebas();
        miku.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelGeneralMouseClicked

    private void jPanelMesa10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa10MouseClicked
        Mesa10 miku = new Mesa10();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa10MouseClicked

    private void jPanelMesa10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa10MouseEntered
        jPanelMesa10.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa10MouseEntered

    private void jPanelMesa10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa10MouseExited
//        jPanelMesa10.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa10MouseExited

    private void jPanelMesa15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa15MouseClicked
        Mesa15 miku = new Mesa15();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa15MouseClicked

    private void jPanelMesa15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa15MouseEntered
        jPanelMesa15.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa15MouseEntered

    private void jPanelMesa15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa15MouseExited
//        jPanelMesa15.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa15MouseExited

    private void jPanelMesa12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa12MouseClicked
        Mesa12 miku = new Mesa12();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa12MouseClicked

    private void jPanelMesa12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa12MouseEntered
        jPanelMesa12.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa12MouseEntered

    private void jPanelMesa12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa12MouseExited
//        jPanelMesa12 .setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa12MouseExited

    private void jPanelMesa13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa13MouseClicked
        Mesa13 miku = new Mesa13();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa13MouseClicked

    private void jPanelMesa13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa13MouseEntered
        jPanelMesa13.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa13MouseEntered

    private void jPanelMesa13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa13MouseExited
//        jPanelMesa13.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa13MouseExited

    private void jPanelMesa14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa14MouseClicked
        Mesa14 miku = new Mesa14();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa14MouseClicked

    private void jPanelMesa14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa14MouseEntered
        jPanelMesa14.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa14MouseEntered

    private void jPanelMesa14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa14MouseExited
//        jPanelMesa14.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa14MouseExited

    private void jPanelMesa011MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa011MouseClicked
        Mesa11 miku = new Mesa11();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelMesa011MouseClicked

    private void jPanelMesa011MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa011MouseEntered
        jPanelMesa011.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelMesa011MouseEntered

    private void jPanelMesa011MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMesa011MouseExited
//        jPanelMesa011.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelMesa011MouseExited

    private void jPanelPalapa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa2MouseClicked
        Palapa2 miku = new Palapa2();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelPalapa2MouseClicked

    private void jPanelPalapa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa2MouseEntered
        jPanelPalapa2.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelPalapa2MouseEntered

    private void jPanelPalapa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa2MouseExited
//        jPanelPalapa2.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelPalapa2MouseExited

    private void jPanelPalapa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa3MouseClicked
        Palapa3 miku = new Palapa3();
        miku.setSize(1330,624);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }//GEN-LAST:event_jPanelPalapa3MouseClicked

    private void jPanelPalapa3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa3MouseEntered
        jPanelPalapa3.setBackground(new Color(246,229,186));
    }//GEN-LAST:event_jPanelPalapa3MouseEntered

    private void jPanelPalapa3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPalapa3MouseExited
//        jPanelPalapa3.setBackground(new Color(90,185,225));
    }//GEN-LAST:event_jPanelPalapa3MouseExited
public void mostrarg (){
            JPanelGenreal miku = new JPanelGenreal();
        miku.setSize(950, 580);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
}
private void Cerrar(){
    String botones [] = {"Cerrar", "Cancelar"};
    int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicacion?", "ATENCIÓN",
            0, 2, null, botones,this);
    if(eleccion==JOptionPane.YES_OPTION){
        System.exit(0);
    }else if (eleccion==JOptionPane.NO_OPTION){
        JOptionPane.showMessageDialog(null,"Se cancelo el cierre de la aplicacion");
    
    }
}
private void contraseña(){
    JOptionPane.showInputDialog(null, "Porfavor ingrese la contraseña",cont);
    if(cont==("password")){
        JPanelAgregarProductos miku = new JPanelAgregarProductos();
        miku.setSize(1140, 560);
        miku.setLocation(0,0);
        jPanelAcciones.removeAll();
        jPanelAcciones.add(miku, BorderLayout.CENTER);
        jPanelAcciones.revalidate();
        jPanelAcciones.repaint();
    }else{
        JOptionPane.showMessageDialog(null,"Contraseña incorrecta");
    }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnInventario;
    private javax.swing.JPanel JpanelMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanelAcciones;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelMesa011;
    private javax.swing.JPanel jPanelMesa1;
    private javax.swing.JPanel jPanelMesa10;
    private javax.swing.JPanel jPanelMesa12;
    private javax.swing.JPanel jPanelMesa13;
    private javax.swing.JPanel jPanelMesa14;
    private javax.swing.JPanel jPanelMesa15;
    private javax.swing.JPanel jPanelMesa2;
    private javax.swing.JPanel jPanelMesa3;
    private javax.swing.JPanel jPanelMesa4;
    private javax.swing.JPanel jPanelMesa5;
    private javax.swing.JPanel jPanelMesa6;
    private javax.swing.JPanel jPanelMesa7;
    private javax.swing.JPanel jPanelMesa8;
    private javax.swing.JPanel jPanelMesa9;
    private javax.swing.JPanel jPanelPalapa1;
    private javax.swing.JPanel jPanelPalapa2;
    private javax.swing.JPanel jPanelPalapa3;
    private javax.swing.JPanel jPanelVisualizar;
    private javax.swing.JLabel jlabelfondo;
    // End of variables declaration//GEN-END:variables
}
