package Ventanas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cruzh
 */
public class JPanelCuentas extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCuentas
     */
    public JPanelCuentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCuenta3 = new javax.swing.JLabel();
        BtnCuenta4 = new javax.swing.JLabel();
        BtnCuenta5 = new javax.swing.JLabel();
        BtnCuenta6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(186, 202, 246));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        BtnCuenta3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta3.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta3.setText("Cerrar cuenta");
        BtnCuenta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnCuenta4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta4.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta4.setText("Agregar cuenta");
        BtnCuenta4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnCuenta5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta5.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta5.setText("Eliminar cuenta");
        BtnCuenta5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnCuenta6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta6.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta6.setText("Vizualizar cuenta");
        BtnCuenta6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCuenta4)
                    .addComponent(BtnCuenta3)
                    .addComponent(BtnCuenta5)
                    .addComponent(BtnCuenta6))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BtnCuenta4)
                .addGap(18, 18, 18)
                .addComponent(BtnCuenta5)
                .addGap(18, 18, 18)
                .addComponent(BtnCuenta3)
                .addGap(18, 18, 18)
                .addComponent(BtnCuenta6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        
    }//GEN-LAST:event_jPanel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCuenta3;
    private javax.swing.JLabel BtnCuenta4;
    private javax.swing.JLabel BtnCuenta5;
    private javax.swing.JLabel BtnCuenta6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
