package Ventanas;


import mesas.GettersandSetters;
import Conexiones.conexionconsqllite;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cruzh
 */
public class JPanelVisualizarCuentas extends javax.swing.JPanel {
    
    Connection cn = conexionconsqllite.getConexion();
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form JPanelVisualizarCuentas
     */
    public JPanelVisualizarCuentas() {
        initComponents();
        jTblVisulizarCuentas.setBackground( new Color(246,229,186));
        jTableProductosBuscados.setBackground( new Color(246,229,186));
//        Mostrar("");
        this.mostrardatosG();
//        this.mostardatosP();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblVisulizarCuentas = new javax.swing.JTable();
        BtnEliminar = new javax.swing.JLabel();
        BtnCuenta9 = new javax.swing.JLabel();
        LabelBuscar = new javax.swing.JLabel();
        BtnCuenta11 = new javax.swing.JLabel();
        BtnCuenta12 = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JLabel();
        BtnAgregar1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductosBuscados = new javax.swing.JTable();
        BtnCuenta13 = new javax.swing.JLabel();
        BtnCuenta14 = new javax.swing.JLabel();
        jTxtBuscarP1 = new javax.swing.JTextField();
        txtNombreP = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        BtnCuenta15 = new javax.swing.JLabel();
        LabelBuscar1 = new javax.swing.JLabel();
        LabelBuscar2 = new javax.swing.JLabel();
        LabelBuscar3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(90, 185, 225));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTblVisulizarCuentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTblVisulizarCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Productos consumidops", "Cantidad", "$ Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblVisulizarCuentas.setRowHeight(25);
        jTblVisulizarCuentas.setSelectionBackground(new java.awt.Color(245, 215, 157));
        jTblVisulizarCuentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblVisulizarCuentas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 430, 350));

        BtnEliminar.setBackground(new java.awt.Color(246, 229, 186));
        BtnEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setText("  Eliminar");
        BtnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });
        add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 130, 50));

        BtnCuenta9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta9.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta9.setText("Mesero: Emmanuel");
        BtnCuenta9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnCuenta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 310, -1));

        LabelBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LabelBuscar.setForeground(new java.awt.Color(0, 0, 0));
        LabelBuscar.setText("Precio");
        LabelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(LabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 70, -1));

        BtnCuenta11.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta11.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta11.setText("Folio: 01");
        BtnCuenta11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnCuenta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, -1));

        BtnCuenta12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta12.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta12.setText("Tabla productos buscados");
        BtnCuenta12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnCuenta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 290, -1));

        BtnEditar.setBackground(new java.awt.Color(246, 229, 186));
        BtnEditar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(0, 0, 0));
        BtnEditar.setText("   Editar ");
        BtnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEditarMouseExited(evt);
            }
        });
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 130, 50));

        BtnAgregar1.setBackground(new java.awt.Color(250, 186, 86));
        BtnAgregar1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnAgregar1.setForeground(new java.awt.Color(0, 0, 0));
        BtnAgregar1.setText("  Agregar ");
        BtnAgregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAgregar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgregar1MouseExited(evt);
            }
        });
        add(BtnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 130, 50));

        jTableProductosBuscados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre P", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductosBuscados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosBuscadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProductosBuscados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 440, 350));

        BtnCuenta13.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta13.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta13.setText("Numero de mesa: 1");
        BtnCuenta13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnCuenta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 220, -1));

        BtnCuenta14.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta14.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta14.setText("Tabla productos en mesa");
        BtnCuenta14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnCuenta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 290, -1));

        jTxtBuscarP1.setBackground(new java.awt.Color(255, 153, 102));
        jTxtBuscarP1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTxtBuscarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBuscarP1ActionPerformed(evt);
            }
        });
        jTxtBuscarP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtBuscarP1KeyReleased(evt);
            }
        });
        add(jTxtBuscarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 310, 40));

        txtNombreP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePActionPerformed(evt);
            }
        });
        add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 340, 40));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 120, 40));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 110, 40));

        BtnCuenta15.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BtnCuenta15.setForeground(new java.awt.Color(0, 0, 0));
        BtnCuenta15.setText("Total: $ 270");
        BtnCuenta15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnCuenta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 170, -1));

        LabelBuscar1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LabelBuscar1.setForeground(new java.awt.Color(0, 0, 0));
        LabelBuscar1.setText("Buscar:");
        LabelBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(LabelBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        LabelBuscar2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LabelBuscar2.setForeground(new java.awt.Color(0, 0, 0));
        LabelBuscar2.setText("Nombre Producto");
        LabelBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(LabelBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 210, -1));

        LabelBuscar3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LabelBuscar3.setForeground(new java.awt.Color(0, 0, 0));
        LabelBuscar3.setText("Cantidad");
        LabelBuscar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(LabelBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
//        JPnalelBuscarProductos.setVisible(true);  
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditarMouseClicked

    private void BtnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseEntered
        BtnEditar.setBackground(Color.orange);
    }//GEN-LAST:event_BtnEditarMouseEntered

    private void BtnAgregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregar1MouseClicked
        conexionconsqllite objConexion = new conexionconsqllite();  // Creamos una conexion para poder insertar la informacion
        GettersandSetters oUsuarios = recuperarDatosGUI();  //Obtencion de datos atraves de la interfaz grafica
        String strSentenciaInsert = String.format("INSERT INTO Mesa1 (PConsumidos,Cantidad,Precio) "   //Aqui se inserta la informacion
                + "VALUES ('%s', '%s' , '%s')", oUsuarios.getNombreProducto(), oUsuarios.getCantidad(),oUsuarios.getPrecio());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert); //Aqui se ejecuta la informacion
        this.mostrardatosG();
    }//GEN-LAST:event_BtnAgregar1MouseClicked

    private void BtnAgregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregar1MouseEntered
        BtnAgregar1.setBackground(Color.orange);
    }//GEN-LAST:event_BtnAgregar1MouseEntered

    private void BtnAgregar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregar1MouseExited
        BtnAgregar1.setBackground(new Color (186,202,246));
    }//GEN-LAST:event_BtnAgregar1MouseExited

    private void BtnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseExited
        BtnEditar.setBackground(new Color (186,202,246));
    }//GEN-LAST:event_BtnEditarMouseExited

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
        BtnEliminar.setBackground(Color.orange);
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
         BtnEditar.setBackground(new Color (186,202,246));
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void jTableProductosBuscadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosBuscadosMouseClicked
       if (evt.getClickCount()==1){
            JTable receptor = (JTable) evt.getSource();
            txtNombreP.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            txtCantidad.setText((receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString()));
            txtPrecio.setText((receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString()));
    }//GEN-LAST:event_jTableProductosBuscadosMouseClicked
    }
    private void jTxtBuscarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBuscarP1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableProductosBuscados.getModel();
        String[] registros = new String[200];
        String sql = "SELECT * FROM Productos WHERE NombreProducto LIKE '%" + jTxtBuscarP1.getText() + "%' ";
        Connection conect = conexionconsqllite.getConexion();
        try
        {
            st = (Statement) conect.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("NombreProducto");
                registros[1] = rs.getString("Cantidad");
                registros[2] = rs.getString("Precio");
                model.addRow(registros);
            }
            jTableProductosBuscados.clearSelection();
            jTableProductosBuscados.setModel(model);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }
    }//GEN-LAST:event_jTxtBuscarP1ActionPerformed

    private void txtNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void jTxtBuscarP1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBuscarP1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBuscarP1KeyReleased
    public void mostrardatosG(){
        DefaultTableModel model = (DefaultTableModel) jTblVisulizarCuentas.getModel();
        while (model.getRowCount()>0){
            model.removeRow(0);
        }
        conexionconsqllite objConexion = new conexionconsqllite();
         try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Mesa1");
            while (resultado.next()) {
                System.err.println(resultado.getString("PConsumidos"));
                System.err.println(resultado.getString("Cantidad"));
                System.err.println(resultado.getString("Precio"));
                       Object[] oUsuario = {resultado.getString("PConsumidos"),resultado.getString("Cantidad"), resultado.getString("Precio")};
                       model.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        

    }
        public void mostardatosP(){
        DefaultTableModel model = (DefaultTableModel) jTableProductosBuscados.getModel();
        while (model.getRowCount()>0){
            model.removeRow(0);
        }
        conexionconsqllite objConexion = new conexionconsqllite();
         try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Productos");
            while (resultado.next()) {
                System.err.println(resultado.getString("NombreProducto"));
                System.err.println(resultado.getString("Cantidad"));
                System.err.println(resultado.getString("Precio"));;
                       Object[] oUsuario = {resultado.getString("NombreProducto"),resultado.getString("Cantidad"), resultado.getString("Precio")};
                       model.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        

    }
    
     public GettersandSetters recuperarDatosGUI(){
    GettersandSetters oUsuarios = new GettersandSetters();
    int Precio = (txtPrecio.getText().isEmpty())?0: Integer.parseInt(txtPrecio.getText());
    oUsuarios.setPrecio(Precio);
    int Cantidad = (txtCantidad.getText().isEmpty())?0: Integer.parseInt(txtCantidad.getText());
    oUsuarios.setCantidad(Cantidad);
    oUsuarios.setNombreProducto(txtNombreP.getText());
    return oUsuarios;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAgregar1;
    private javax.swing.JLabel BtnCuenta11;
    private javax.swing.JLabel BtnCuenta12;
    private javax.swing.JLabel BtnCuenta13;
    private javax.swing.JLabel BtnCuenta14;
    private javax.swing.JLabel BtnCuenta15;
    private javax.swing.JLabel BtnCuenta9;
    private javax.swing.JLabel BtnEditar;
    private javax.swing.JLabel BtnEliminar;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelBuscar1;
    private javax.swing.JLabel LabelBuscar2;
    private javax.swing.JLabel LabelBuscar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProductosBuscados;
    private javax.swing.JTable jTblVisulizarCuentas;
    private javax.swing.JTextField jTxtBuscarP1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}

